AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket
Parameters:
  BucketName:
    Type: String
    Description: BucketName
    Default: sharath-test-bkt
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket